### ISSUE TITLE
Result of `view_blocksbysm.py` sometimes unreadable

### ISSUE THREAD

**Issue by Wen-He** [yalue/cuda_scheduling_examiner_mirror#2]
My GPU has 30 SMs. If I launch a kernel with too many small blocks (eg. 1024 blocks with 256 threads each), the result of `view_blocksbysm.py` will be unreadable even if in full screen mode.
![Screenshot of `tk`](https://user-images.githubusercontent.com/18651139/67291636-6c802800-f514-11e9-8f49-2d327c7f0b78.png)
 Is there any way to make the result readable? And is there any way to save the result in eps format?

**Comment by yalue** [comment]
Hi!  Thanks for taking the time to open an issue, and sorry about my slow response.  At the moment we don't have a good stable way to do this, but you can try the following adjusted version of `view_blocksbysm.py` to see if it helps.  I modified it to take a `--min-sm` and `--max-sm` argument so you can specify a range of SMs to include in the display.  For example, `python scripts/view_blocksbysm.py --min-sm 5 --max-sm 10` should only display SMs 5 through 9.  Unfortunately, my modifications aren't that clean and I see some issues with the script drawing blocks outside of where it should, but it should at least help you zoom in on detail. (I didn't write the original script and only quickly modified the code.)  If you felt like contributing your own updated version, I'd be happy to take a PR!

Anyway, the modified version of `view_blocksbysm.py` is [here](https://gist.github.com/yalue/c10ce129097d621173afd4c096fa9e22).

**Comment by Wen-He** [comment]
Thanks for your modification. It's able to meet my need. But I encounter a new problem. If multiple kernel launch at the same time, only a few of the arrows showing kernels' launch time will be displayed in the `tk` GUI.

![Screenshot from 2019-11-07 17-00-49](https://user-images.githubusercontent.com/18651139/68374630-367fac80-0180-11ea-9e9d-abe0a98be605.png)

**Comment by yalue** [comment]
Hello again,  I have spoken to my colleague who wrote the script, who is working on a modification, but unfortunately is unable to prioritize it so I don't know when it will be complete.  If you produce a suitable modification in the meantime yourself, then I'd be happy to accept any changes you submit!
